// Deterministic SKU generator, format CHO-{型態縮寫}-{IP縮寫}-{角色縮寫}-001.
// Ported from the branch prototype's SKU rule, but generated by rule code instead
// of asking the LLM -- an LLM-generated SKU can drift between reruns of the same
// product, which is unacceptable for an inventory identifier.

const TYPE_ABBREVIATIONS: Record<string, string> = {
  絨毛娃娃: "PLU",
  吊飾: "CHM",
  鑰匙圈: "KEY",
  盲盒: "BLD",
  扭蛋: "GAC",
  娃娃抱枕: "CSH",
  壓克力立牌: "ACR",
  手機支架: "PHS",
  公仔模型: "FIG",
};

const FALLBACK_ABBREVIATION = "OTH";

function isAsciiAlias(value: string): boolean {
  return /^[A-Za-z]+$/.test(value.trim());
}

function pickAsciiAlias(aliases: string[] | undefined): string | null {
  return aliases?.find(isAsciiAlias)?.trim() ?? null;
}

/** Stable fallback code for names without an English alias yet -- same input always
 * produces the same 3-letter code, so SKUs stay stable across regenerations even
 * before someone fills in a proper alias in ip_catalog / ip_characters. */
function hashToCode(value: string): string {
  const trimmed = value.trim();

  if (!trimmed) {
    return FALLBACK_ABBREVIATION;
  }

  let hash = 0;

  for (const char of trimmed) {
    hash = (hash * 31 + char.codePointAt(0)!) >>> 0;
  }

  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  let code = "";
  let remainder = hash;

  for (let i = 0; i < 3; i += 1) {
    code += alphabet[remainder % alphabet.length];
    remainder = Math.floor(remainder / alphabet.length);
  }

  return code;
}

export interface GenerateSkuInput {
  productType: string;
  ipName: string;
  ipAliases?: string[];
  characterName?: string | null;
  characterAliases?: string[];
}

export interface GenerateSkuResult {
  sku: string;
  usedFallbackAbbreviation: boolean;
}

export function generateSku(input: GenerateSkuInput): GenerateSkuResult {
  const typeCode = TYPE_ABBREVIATIONS[input.productType] ?? FALLBACK_ABBREVIATION;

  const ipAlias = pickAsciiAlias(input.ipAliases);
  const ipCode = ipAlias ? ipAlias.slice(0, 3).toUpperCase() : hashToCode(input.ipName);

  const characterAlias = pickAsciiAlias(input.characterAliases);
  const characterCode = input.characterName
    ? characterAlias
      ? characterAlias.slice(0, 3).toUpperCase()
      : hashToCode(input.characterName)
    : "GEN";

  const usedFallbackAbbreviation =
    typeCode === FALLBACK_ABBREVIATION || !ipAlias || (Boolean(input.characterName) && !characterAlias);

  return {
    sku: `CHO-${typeCode}-${ipCode}-${characterCode}-001`,
    usedFallbackAbbreviation,
  };
}
